//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.5448
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace Rfc {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.rfc-editor.org/rfc-index")]
    [XmlRoot(Namespace="http://www.rfc-editor.org/rfc-index", IsNullable=false)]
    public partial class author {
        
        private string nameField;
        
        private string titleField;
        
        private string organizationField;
        
        private string orgabbrevField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("org-abbrev")]
        public string orgabbrev {
            get {
                return this.orgabbrevField;
            }
            set {
                this.orgabbrevField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.rfc-editor.org/rfc-index")]
    [XmlRoot(Namespace="http://www.rfc-editor.org/rfc-index", IsNullable=false)]
    public partial class date {
        
        private monthName monthField;
        
        private string dayField;
        
        private string yearField;
        
        /// <remarks/>
        public monthName month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="integer")]
        public string day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="gYear")]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }

		public override string ToString()
		{
			return String.Format("{0}-{1}-{2}", year, month, day);
		}
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(Namespace="http://www.rfc-editor.org/rfc-index")]
    public enum monthName {
        
        /// <remarks/>
        January,
        
        /// <remarks/>
        February,
        
        /// <remarks/>
        March,
        
        /// <remarks/>
        April,
        
        /// <remarks/>
        May,
        
        /// <remarks/>
        June,
        
        /// <remarks/>
        July,
        
        /// <remarks/>
        August,
        
        /// <remarks/>
        September,
        
        /// <remarks/>
        October,
        
        /// <remarks/>
        November,
        
        /// <remarks/>
        December,
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.rfc-editor.org/rfc-index")]
    [XmlRoot(Namespace="http://www.rfc-editor.org/rfc-index", IsNullable=false)]
    public partial class format {
        
        private fileFormat fileformatField;
        
        private string charcountField;
        
        private string pagecountField;
        
        /// <remarks/>
        [XmlElement("file-format")]
        public fileFormat fileformat {
            get {
                return this.fileformatField;
            }
            set {
                this.fileformatField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("char-count", DataType="nonNegativeInteger")]
        public string charcount {
            get {
                return this.charcountField;
            }
            set {
                this.charcountField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("page-count", DataType="nonNegativeInteger")]
        public string pagecount {
            get {
                return this.pagecountField;
            }
            set {
                this.pagecountField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(Namespace="http://www.rfc-editor.org/rfc-index")]
    public enum fileFormat {
        
        /// <remarks/>
        ASCII,
        
        /// <remarks/>
        PS,
        
        /// <remarks/>
        PDF,
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.rfc-editor.org/rfc-index")]
    [XmlRoot(Namespace="http://www.rfc-editor.org/rfc-index", IsNullable=false)]
    public partial class keywords {
        
        private string[] kwField;
        
        /// <remarks/>
        [XmlElement("kw")]
        public string[] kw {
            get {
                return this.kwField;
            }
            set {
                this.kwField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.rfc-editor.org/rfc-index")]
    [XmlRoot("std-entry", Namespace="http://www.rfc-editor.org/rfc-index", IsNullable=false)]
    public partial class stdentry {
        
        private string docidField;
        
        private string titleField;
        
        private string[] isalsoField;
        
        /// <remarks/>
        [XmlElement("doc-id")]
        public string docid {
            get {
                return this.docidField;
            }
            set {
                this.docidField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayAttribute("is-also")]
        [XmlArrayItemAttribute("doc-id", IsNullable=false)]
        public string[] isalso {
            get {
                return this.isalsoField;
            }
            set {
                this.isalsoField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.rfc-editor.org/rfc-index")]
    [XmlRoot("bcp-entry", Namespace="http://www.rfc-editor.org/rfc-index", IsNullable=false)]
    public partial class bcpentry {
        
        private string docidField;
        
        private string titleField;
        
        private string[] isalsoField;
        
        /// <remarks/>
        [XmlElement("doc-id")]
        public string docid {
            get {
                return this.docidField;
            }
            set {
                this.docidField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayAttribute("is-also")]
        [XmlArrayItemAttribute("doc-id", IsNullable=false)]
        public string[] isalso {
            get {
                return this.isalsoField;
            }
            set {
                this.isalsoField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.rfc-editor.org/rfc-index")]
    [XmlRoot("fyi-entry", Namespace="http://www.rfc-editor.org/rfc-index", IsNullable=false)]
    public partial class fyientry {
        
        private string docidField;
        
        private string titleField;
        
        private string[] isalsoField;
        
        /// <remarks/>
        [XmlElement("doc-id")]
        public string docid {
            get {
                return this.docidField;
            }
            set {
                this.docidField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayAttribute("is-also")]
        [XmlArrayItemAttribute("doc-id", IsNullable=false)]
        public string[] isalso {
            get {
                return this.isalsoField;
            }
            set {
                this.isalsoField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.rfc-editor.org/rfc-index")]
    [XmlRoot("rfc-entry", Namespace="http://www.rfc-editor.org/rfc-index", IsNullable=false)]
    public partial class rfcentry {
        
        private string docidField;
        
        private string titleField;
        
        private author[] authorField;
        
        private date dateField;
        
        private format[] formatField;
        
        private string[] keywordsField;
        
        private string[] abstractField;
        
        private string draftField;
        
        private string notesField;
        
        private string[] obsoletesField;
        
        private string[] obsoletedbyField;
        
        private string[] updatesField;
        
        private string[] updatedbyField;
        
        private string[] isalsoField;
        
        private string[] seealsoField;
        
        private status currentstatusField;
        
        private status publicationstatusField;
        
        private stream streamField;
        
        private bool streamFieldSpecified;
        
        private string areaField;
        
        private string wg_acronymField;
        
        private string errataurlField;
        
        /// <remarks/>
        [XmlElement("doc-id")]
        public string docid {
            get {
                return this.docidField;
            }
            set {
                this.docidField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("author")]
        public author[] author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        public date date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("format")]
        public format[] format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItemAttribute("kw", IsNullable=false)]
        public string[] keywords {
            get {
                return this.keywordsField;
            }
            set {
                this.keywordsField = value;
            }
        }

		[XmlIgnore]
		public string KeywordList
		{
			get
			{
				if (keywords == null || keywords.Length == 0)
					return String.Empty;
				return String.Join(";", keywords);
			}
		}
        
        /// <remarks/>
        [XmlArrayItemAttribute("p", IsNullable=false)]
        public string[] @abstract {
            get {
                return this.abstractField;
            }
            set {
                this.abstractField = value;
            }
        }
        
        /// <remarks/>
        public string draft {
            get {
                return this.draftField;
            }
            set {
                this.draftField = value;
            }
        }
        
        /// <remarks/>
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItemAttribute("doc-id", IsNullable=false)]
        public string[] obsoletes {
            get {
                return this.obsoletesField;
            }
            set {
                this.obsoletesField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayAttribute("obsoleted-by")]
        [XmlArrayItemAttribute("doc-id", IsNullable=false)]
        public string[] obsoletedby {
            get {
                return this.obsoletedbyField;
            }
            set {
                this.obsoletedbyField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItemAttribute("doc-id", IsNullable=false)]
        public string[] updates {
            get {
                return this.updatesField;
            }
            set {
                this.updatesField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayAttribute("updated-by")]
        [XmlArrayItemAttribute("doc-id", IsNullable=false)]
        public string[] updatedby {
            get {
                return this.updatedbyField;
            }
            set {
                this.updatedbyField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayAttribute("is-also")]
        [XmlArrayItemAttribute("doc-id", IsNullable=false)]
        public string[] isalso {
            get {
                return this.isalsoField;
            }
            set {
                this.isalsoField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayAttribute("see-also")]
        [XmlArrayItemAttribute("doc-id", IsNullable=false)]
        public string[] seealso {
            get {
                return this.seealsoField;
            }
            set {
                this.seealsoField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("current-status")]
        public status currentstatus {
            get {
                return this.currentstatusField;
            }
            set {
                this.currentstatusField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("publication-status")]
        public status publicationstatus {
            get {
                return this.publicationstatusField;
            }
            set {
                this.publicationstatusField = value;
            }
        }
        
        /// <remarks/>
        public stream stream {
            get {
                return this.streamField;
            }
            set {
                this.streamField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnoreAttribute()]
        public bool streamSpecified {
            get {
                return this.streamFieldSpecified;
            }
            set {
                this.streamFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        public string wg_acronym {
            get {
                return this.wg_acronymField;
            }
            set {
                this.wg_acronymField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("errata-url")]
        public string errataurl {
            get {
                return this.errataurlField;
            }
            set {
                this.errataurlField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(Namespace="http://www.rfc-editor.org/rfc-index")]
    public enum status {
        
        /// <remarks/>
        STANDARD,
        
        /// <remarks/>
        [XmlEnumAttribute("DRAFT STANDARD")]
        DRAFTSTANDARD,
        
        /// <remarks/>
        [XmlEnumAttribute("PROPOSED STANDARD")]
        PROPOSEDSTANDARD,
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        [XmlEnumAttribute("BEST CURRENT PRACTICE")]
        BESTCURRENTPRACTICE,
        
        /// <remarks/>
        [XmlEnumAttribute("FOR YOUR INFORMATION")]
        FORYOURINFORMATION,
        
        /// <remarks/>
        EXPERIMENTAL,
        
        /// <remarks/>
        HISTORIC,
        
        /// <remarks/>
        INFORMATIONAL,
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(Namespace="http://www.rfc-editor.org/rfc-index")]
    public enum stream {
        IETF,
        IAB,
        IRTF,
        INDEPENDENT,
        Legacy,
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.rfc-editor.org/rfc-index")]
    [XmlRoot("rfc-not-issued-entry", Namespace="http://www.rfc-editor.org/rfc-index", IsNullable=false)]
    public partial class rfcnotissuedentry {
        
        private string docidField;
        
        /// <remarks/>
        [XmlElement("doc-id")]
        public string docid {
            get {
                return this.docidField;
            }
            set {
                this.docidField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.rfc-editor.org/rfc-index")]
    [XmlRoot("rfc-index", Namespace="http://www.rfc-editor.org/rfc-index", IsNullable=false)]
    public partial class rfcindex {
        
        private stdentry[] stdentryField;
        
        private bcpentry[] bcpentryField;
        
        private fyientry[] fyientryField;
        
        private rfcentry[] rfcentryField;
        
        private rfcnotissuedentry[] rfcnotissuedentryField;
        
        private string titleField;
        
        /// <remarks/>
        [XmlElement("std-entry")]
        public stdentry[] stdentry {
            get {
                return this.stdentryField;
            }
            set {
                this.stdentryField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("bcp-entry")]
        public bcpentry[] bcpentry {
            get {
                return this.bcpentryField;
            }
            set {
                this.bcpentryField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("fyi-entry")]
        public fyientry[] fyientry {
            get {
                return this.fyientryField;
            }
            set {
                this.fyientryField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("rfc-entry")]
        public rfcentry[] rfcentry {
            get {
                return this.rfcentryField;
            }
            set {
                this.rfcentryField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("rfc-not-issued-entry")]
        public rfcnotissuedentry[] rfcnotissuedentry {
            get {
                return this.rfcnotissuedentryField;
            }
            set {
                this.rfcnotissuedentryField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
}
